"""Experiment08 reporting; reads frozen results without changing predictions."""
import sys,os,json,base64,html,shutil,zipfile,platform
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parent;OUT=ROOT.parent/'outputs';R=ROOT/'accounts_results'
os.environ['MPLCONFIGDIR']=str(ROOT/'accounts_mpl_cache')
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from accounts_reader import score
from accounts_portable import prepare

LABELS={'exact':'Intact','transpose':'Transposition','detune':'One detuned note','timing':'One delayed note','delete_rest':'Missing note, retained rest','delete_closed':'Missing note, closed gap','delete_two':'Two missing notes','substitute':'Pitch substitution','insert':'Extra note','delete_insert':'Missing + extra note','weak_present':'Weak note still present','mask_present':'Mask, note present','mask_absent':'Mask, note absent','merged':'Merged observations','legitimate_rest':'Longer pause, all notes present','delete_transpose':'Missing + transposition','delete_timing':'Missing + timing change','delete_detune':'Missing + detuned note'}
def load(p):return json.loads(Path(p).read_text())
def embed(p,mime):return f'data:{mime};base64,'+base64.b64encode(Path(p).read_bytes()).decode()
def image(path,alt):return f'<img src="{embed(path,"image/png")}" alt="{html.escape(alt)}">'
def audio(b):return f'<audio controls preload="none" src="{embed(b["audio_path"],"audio/wav")}"></audio>'
def main():
    s=load(R/'summary.json');diag=load(R/'posthoc_diagnostics.json')['families'];cfg=load(R/'frozen_config.json');audit=load(R/'audit.json');replay=load(R/'replay_summary.json');portable=load(R/'portable_validation.json');manifest=load(ROOT/'accounts_stimuli/manifest.json');B={b['id']:b for b in manifest['blocks']};details={d['query_id']:d for d in load(R/'query_details.json')};pairs=load(R/'held_out_pairs.json');families=manifest['core_families']+manifest['stack_order'];ranked=sum(d['unique_top_score_true'] for d in diag.values())
    assert ranked==553 and s['primary_by_method']['accounts']['correct_singletons']==164
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':11,'axes.spines.top':False,'axes.spines.right':False})
    fig,ax=plt.subplots(figsize=(11.5,9));y=np.arange(len(families))
    ax.barh(y,[diag[f]['unique_top_score_true'] for f in families],color='#d6e2e5',height=.68,label='Correct memory ranked first (rejection ignored)')
    ax.barh(y,[s['families'][f]['correct_singletons'] for f in families],color='#14786b',height=.36,label='Correct memory actually accepted')
    ax.set_yticks(y,labels=[LABELS[f] for f in families]);ax.invert_yaxis();ax.set_xlim(0,35);ax.set_xticks([0,8,16,24,32]);ax.set_xlabel('Cases out of 32 per family · 16 held-out phrase groups')
    for k,f in enumerate(families):ax.text(s['families'][f]['correct_singletons']+.35,k,str(s['families'][f]['correct_singletons']),va='center',fontsize=10,color='#064d45')
    ax.axhline(14.5,color='#87989d',lw=1,ls='--');ax.legend(loc='upper center',bbox_to_anchor=(.5,-.085),frameon=False,fontsize=10,ncol=1);ax.grid(axis='x',alpha=.17);ax.set_axisbelow(True);ax.set_title('Ranking is often right; acceptance is the bottleneck',loc='left',pad=18,fontweight='bold')
    fig.tight_layout();chart=OUT/'competing-accounts-results.png';fig.savefig(chart,dpi=150,bbox_inches='tight');plt.close(fig)
    fig,axes=plt.subplots(2,1,figsize=(11,5.8),sharex=True)
    rid='e09_reference_a'
    with np.load(ROOT/'accounts_features'/f'{rid}.npz') as z:ref={k:z[k] for k in z.files}
    for ax,f,title in zip(axes,('delete_rest','weak_present'),('Omitted note: quiet at the predicted location','Weak note: no detected event, but energy remains')):
        qid='e09_query_a_'+f
        with np.load(ROOT/'accounts_features'/f'{qid}.npz') as z:q={k:z[k] for k in z.files}
        p=details[qid]['accepted'][0]['accounts'][0];gap=p['missing_evidence'][0];lo,hi=gap['expected_interval_s']
        ax.plot(ref['frame_time_s'],np.maximum(ref['frame_rms'],1e-6),c='#9cb1b8',ls='--',lw=1.3,label='Stored acoustic trace')
        ax.plot(q['frame_time_s'],np.maximum(q['frame_rms'],1e-6),c='#14786b',lw=1.6,label='Current acoustic trace')
        ax.axvspan(lo,hi,color='#d9a850',alpha=.2,label='Predicted location from alignment');ax.axhline(gap['quiet_threshold_rms'],c='#9b531a',lw=1,ls=':',label='Quiet threshold')
        ax.set_yscale('log');ax.set_ylim(1e-6,.4);ax.set_ylabel('RMS amplitude (log)');ax.set_title(title,loc='left',fontsize=12,fontweight='bold');ax.grid(alpha=.13)
    axes[-1].set_xlim(.48,.91);axes[-1].set_xlabel('Seconds within the completed query block');axes[-1].legend(loc='upper center',bbox_to_anchor=(.5,-.3),ncol=2,frameon=False,fontsize=9);fig.tight_layout();observation=OUT/'competing-accounts-observations.png';fig.savefig(observation,dpi=150,bbox_inches='tight');plt.close(fig)
    metric_note={'applicability':'Joint recovery metrics apply to accounts only. The baseline rows in trials.json contain null joint fields. summary.json sums these to zero; those baseline zeros mean NOT EVALUATED, not failed recovery.',
        'ordinary_origin':'Ordinary retrieval scores use constructed source provenance; they are not human identity judgments. An absent-origin false acceptance does not establish perceptual dissimilarity.',
        'recovery':'Strict correspondence recovery checks the programmed event mapping. Substitution versus deletion-plus-insertion can fit the same sound; hidden construction history is not uniquely audible.',
        'observation':'Weak/masked/merged cases have separate observation metrics; strict full physical recovery is impossible when the corresponding event is undetected. Masked rejections are not counted as successful uncertainty-aware memory retrieval.',
        'replication':'576 primary queries are clustered in 16 held-out groups. Ambiguity has 16 unique cases evaluated in two memory orders; 32 decisions are not 32 independent cases.',
        'diagnostics':'Top-rank and known-reference ceilings are post-hoc analyses of frozen outputs, not acceptance results or new tuned models.'}
    (R/'metric_definition_note.json').write_text(json.dumps(metric_note,indent=2)+'\n')
    fullrows=''.join(f'<tr><td>{LABELS[f]}</td><td>{diag[f]["unique_top_score_true"]}/32</td><td><b>{s["families"][f]["correct_singletons"]}/32</b></td><td>{s["families"][f]["joint_best"]}/32</td><td>{diag[f]["direct_best_alignment"]}/32</td><td>{diag[f]["direct_account_set"]}/32</td></tr>' for f in families)
    baselines=''.join(f'<tr><td>{name}</td><td>{s["primary_by_method"][m]["correct_singletons"]}/576</td><td>{s["primary_by_method"][m]["absent_false_accept"]}/576</td></tr>' for m,name in [('accounts','Experiment08 support readout'),('old07','Frozen Experiment07 reader'),('count','Event count only'),('envelope','RMS envelope only')])
    lengthrows=''.join(f'<tr><td>{n} events</td><td>{s["lengths"][str(n)]["correct_singletons"]}/144</td><td>{s["lengths"][str(n)]["joint_best"]}/144</td></tr>' for n in (4,6,8,10))
    example_cards=[]
    for family,description in [('delete_rest','The fourth reference event has no matched counterpart. The measured energy at its predicted location is below the quiet threshold.'),('weak_present','The same correspondence gap remains, but the energy trace prevents a quiet-gap assertion. The note is physically present in this construction.'),('mask_present','The correct memory ranks first but falls below the support threshold. The emitted result is unsupported memory; this is not successful retention under masking.'),('delete_detune','Both edits are recoverable with the known reference, but the reader rejects the memory. This illustrates the separation between recovery and acceptance.')]:
        qid='e09_query_a_'+family;value=score(pairs[qid][rid]['evidence'],cfg);selected=details[qid]['accepted'];status='One supported memory' if selected else 'Unsupported memory'
        example_cards.append(f'<article class="sample"><h3>{LABELS[family]}</h3>{audio(B[qid])}<p><b>{status}.</b> Support score {value:.3f}; fixed threshold {cfg["threshold"]:.3f}.</p><p>{description}</p><details><summary>Recorded output</summary><pre>{html.escape(json.dumps(selected,indent=2))}</pre></details></article>')
    text=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Earworm · Experiment08 · Competing accounts</title><style>
    :root{{--ink:#16313e;--muted:#526975;--accent:#14786b;--line:#d8e3e8;--wash:#edf6f3}}*{{box-sizing:border-box}}body{{margin:0;background:#f3f6f7;color:var(--ink);font:17px/1.65 system-ui,-apple-system,sans-serif}}main{{max-width:1160px;margin:auto;background:#fff;padding:55px 58px 72px}}h1{{font-size:46px;line-height:1.13;letter-spacing:-1.5px;max-width:950px}}h2{{font-size:27px;line-height:1.25;margin:42px 0 16px}}h3{{font-size:19px;line-height:1.3}}p{{margin:12px 0}}.eyebrow{{font-size:12px;letter-spacing:.15em;color:var(--accent);font-weight:750;text-transform:uppercase}}.lead{{font-size:22px;line-height:1.5}}.meta,.small,figcaption{{font-size:14px;color:var(--muted)}}.meta{{border-bottom:1px solid var(--line);padding-bottom:20px}}.finding{{padding:22px 25px;background:var(--wash);border-left:5px solid var(--accent);margin:25px 0}}.metrics{{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin:25px 0}}.metric{{border:1px solid var(--line);padding:20px}}.number{{font-size:33px;line-height:1.2;font-weight:750}}figure{{margin:28px 0}}img{{max-width:100%;height:auto}}a{{color:#126879;text-underline-offset:3px}}table{{width:100%;border-collapse:collapse;font-size:15px;margin:18px 0}}th,td{{padding:11px 10px;text-align:left;vertical-align:top;border-bottom:1px solid var(--line)}}th{{background:var(--wash)}}.scroll{{overflow-x:auto}}.samples{{display:grid;grid-template-columns:1fr 1fr;gap:18px}}.sample{{background:#f6f8f9;border:1px solid var(--line);padding:20px}}.sample p{{font-size:15px}}audio{{width:100%;height:40px}}details{{border:1px solid var(--line);padding:12px 15px;margin:15px 0}}summary{{cursor:pointer;font-weight:650}}pre{{font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere;max-height:300px;overflow-y:auto}}.warning{{background:#fff5e7;border-left:5px solid #ae7029;padding:18px 23px}}.downloads{{padding:18px 23px;border:1px solid var(--line)}}@media(max-width:720px){{main{{padding:30px 20px}}h1{{font-size:34px}}.samples,.metrics{{grid-template-columns:1fr}}}}
    </style></head><body><main><p class="eyebrow">Project Earworm / Experiment 08 / Competing accounts</p>
    <h1>The memory often ranks first.<br>The reader still rejects it.</h1>
    <p class="lead">Removing the fixed coverage rule exposed a support-calibration problem. The new reader accepted the correct memory in <b>164/576</b> held-out cases, compared with <b>198/576</b> for the frozen Experiment07 reader. <b>This is not a retrieval improvement.</b></p>
    <p class="meta">September 19, 2026 · 16 held-out phrase groups · 4–10 events · 16 seconds of intervening sound · Existing local Mac setup · Paid external compute: $0</p>
    <div class="metrics"><div class="metric"><div class="number">164 / 576</div><p>Correct memory actually accepted<br><span class="small">156 also passed strict edit recovery</span></p></div><div class="metric"><div class="number">553 / 576</div><p>Correct memory ranked first<br><span class="small">Diagnostic only: ignores rejection</span></p></div><div class="metric"><div class="number">0 / 576</div><p>Absent-source false acceptances<br><span class="small">Observed rate; 16 clustered groups</span></p></div></div>
    <div class="finding"><p><b>The useful boundary:</b> the frozen system can often propose the right correspondence under an edit, but its support rule rejects most damaged phrases. It can preserve uncertainty about a weak observation in a small accepted subset. It has <b>not</b> achieved the requested combination of accepted memory retrieval and causal restraint under masking.</p></div>
    <h2>What changed</h2><p>Each memory keeps the unchanged Experiment05 acoustic description: event pitches and onsets alongside time-preserving energy and spectral traces. The new matcher proposes several monotonic alignments, allowing deletions, insertions, pitch changes, and timing changes. It receives no edit label, expected note count, fixed coverage fraction, or generator pitch sequence.</p>
    <p>A small regularized linear readout fits 12 audio-derived alignment features using four development groups. A separate four-group calibration set selects one support threshold under a 5% empirical absent-source false-acceptance ceiling. Everything is frozen before extraction of the 16 evaluation groups. The three stacked edit families never enter fitting or calibration.</p>
    <p>The edit vocabulary, quality filters, alignment costs, and acoustic evidence rules are supplied by us. Only the small readout is fitted. MERT stays unchanged and is not invoked in this experiment. This does not establish learned perceptual identity or subjective listening.</p>
    <h2>The three control families</h2><table><thead><tr><th>Control</th><th>What was tested</th><th>What it established</th></tr></thead><tbody>
    <tr><td>Counts, gaps, and mixed edits</td><td>4, 6, 8, and 10 events; missing notes with retained or closed gaps; multiple omissions; insertions; unchanged-count deletion-plus-insertion; wrong sources with matching length and timing; legitimate pauses.</td><td>Event count alone rejects everything at its calibrated threshold. Envelope matching has 40/576 absent-source false accepts. Neither reproduces reliable retrieval.</td></tr>
    <tr><td>Observation failure</td><td>Weak notes, masking with a note present or absent, and events that merge in the unchanged detector.</td><td>Eight accepted weak-note cases keep a missing correspondence unresolved because energy remains. All 64 masked cases are rejected. Masking robustness is unproven.</td></tr>
    <tr><td>Genuine ambiguity</td><td>Two different reference phrases generate exactly the same query waveform when their differing event is omitted. Evaluate both memory orders.</td><td>The new reader returns the exact pair for 4/16 unique cases (8/32 order trials), rejecting the other 12. The old reader returns it for 12/16. No hidden unique-origin guess is rewarded.</td></tr>
    </tbody></table>
    <h2>Stacking changes, one test at a time</h2><p>After the core stage, each combination was run sequentially with the same frozen configuration. Each row contains 32 queries across the 16 held-out groups.</p><table><thead><tr><th>Combination</th><th>Correct memory first</th><th>Accepted memory + recovered edits</th></tr></thead><tbody><tr><td>Missing note + transposition</td><td>32/32</td><td>8/32</td></tr><tr><td>Missing note + timing change</td><td>32/32</td><td>8/32</td></tr><tr><td>Missing note + detuned note</td><td>32/32</td><td>0/32</td></tr></tbody></table>
    <p>With the true reference supplied as an oracle, all three combinations recover the programmed correspondence and pitch/onset changes in 32/32 cases. That diagnostic isolates usable acoustic information; it does not count as successful retrieval. The actual emitted decision rejects most of these memories.</p>
    <figure>{image(chart,'Per-family comparison of correct memory ranked first and actually accepted, showing widespread rejection of damaged phrases.')}<figcaption>Ranking is conditional on the true source being present among nine memories. Gray bars are a post-hoc diagnostic, not successful outputs. The dashed line marks the three sequential stacked perturbations.</figcaption></figure>
    <h2>A missing detection does not erase the sound</h2><p>The six-event example below produces the same missing correspondence in two situations. In one, the current energy trace is quiet at the location predicted by the alignment. In the other, a very weak note falls below the event detector’s threshold but remains visible in the retained acoustic trace.</p>
    <figure>{image(observation,'Log-energy plots distinguish an actually quiet omission from a weak note missed by the detector.')}<figcaption>One held-out pair, e09 source A. The original acoustic trace is kept intact. Predicted locations are separate alignment hypotheses. “Quiet at the predicted location” is a measured statement under that hypothesis, not proof of a performer’s intent or the physical cause of a missing note.</figcaption></figure>
    <p>Across all eight correctly accepted weak-note cases, the output retains <b>unresolved observation</b> and makes no quiet-gap assertion. The eight accepted retained-rest omissions have the omitted position correctly localized and quiet acoustic evidence. Closed-gap omissions produce unresolved location evidence in all four accepted cases.</p>
    <div class="warning"><p><b>Masking remains a failure of the integrated system.</b> The correct memory ranks first in all 64 masked-present/masked-absent queries, but none reaches the support threshold. Zero causal claims here must not be presented as successful uncertainty-aware retrieval: the system declined to support any memory.</p></div>
    <h2>Listen to the recorded examples</h2><p class="small">These are construction-labeled demonstrations, not human identity judgments. Audio levels are preserved, including the deliberately weak note. This does not modify the separate human listening pilot.</p>
    <article class="sample"><h3>Stored reference · e09 A</h3>{audio(B[rid])}<p>Six events. The comparison examples below perturb the same reference.</p></article><div class="samples">{''.join(example_cards)}</div>
    <h2>What competing accounts added</h2><p>For the 32 pitch-substitution queries, the best alignment describes deletion plus insertion rather than the generator’s one-event substitution. The programmed correspondence appears in <b>31/32 retained alternative sets</b>, compared with <b>0/32 best paths</b>, when the true reference is supplied. Keeping several accounts therefore preserves an explanation that a single path would discard.</p>
    <p>This is a conditional diagnostic: those memories were not accepted. Also, substitution and deletion-plus-insertion can explain the same observed waveform. The construction record tells us how we generated the audio; it cannot establish that one causal account is uniquely audible. Physical causes remain explicitly unidentified.</p>
    <h2>Full results and denominators</h2><p>There are 576 primary queries: 18 families × two source phrases × 16 held-out groups. The same queries are crossed with source-present and source-absent histories, with 0/16-second delays and intact/reference-drop/full-reset memory controls. These variants are correlated controls, not new independent samples.</p>
    <table><thead><tr><th>Reader</th><th>Accepted correct singleton</th><th>Absent-source false acceptance</th></tr></thead><tbody>{baselines}</tbody></table><p class="small">Count and envelope thresholds are calibrated separately by the same rule. The old reader retains its original threshold and coverage restrictions. Recovery was not rescored for the baseline readers, so no comparative joint-recovery claim is made.</p>
    <div class="scroll"><table><thead><tr><th>Query family</th><th>First by rank</th><th>Accepted source</th><th>Joint best account</th><th>Known-source best</th><th>Known-source account set</th></tr></thead><tbody>{fullrows}</tbody></table></div>
    <p class="small">Each denominator is 32. “Joint” requires the actual uniquely accepted true source and exact missing positions/insertion count, all programmed surviving correspondences, pitch changes within 0.20 semitone, and onset changes within 15 ms. The known-source columns use an oracle and cannot be treated as retrieval. Weak/merged/masked observations also have separate uncertainty metrics because undetected physical events cannot meet full correspondence recovery. Ambiguous construction accounts are not uniquely audible causes.</p>
    <table><thead><tr><th>Reference length</th><th>Accepted source</th><th>Joint recovery</th></tr></thead><tbody>{lengthrows}</tbody></table><p>The damaged phrases accepted beyond intact/transposition/timing/pause controls all come from the six-event groups. Removing a hard coverage gate did not produce a length-general support rule. Four fit groups and four calibration groups are a small development sample; this experiment does not identify a universal remedy.</p>
    <h2>Memory, causality, and availability</h2><p>Batch results are identical at 0 and 16 seconds. Removing the reference or resetting memory removes all source retrieval. A durable store of at most 12 acoustic descriptions is supplied; this is not evidence for learned recurrent memory or resistance to memory interference.</p>
    <p><b>{replay['fresh_trials']} fresh sequential replays</b> recomputed {replay['fresh_blocks']} waveform blocks with no feature or similarity cache, including matched history swaps and reference-drop/full-reset controls. All reproduced the cached decisions. Four additional pairs with different future audio produced identical already-available descriptions and outputs. Query and stored descriptions remained unchanged through inference.</p>
    <p>Each replay records sound arrival, description completion, and output availability after both matching and explanation, with actual wall-clock timestamps. The simulated online schedule gave a median {replay['latency_median_s']*1000:.0f} ms and maximum {replay['latency_max_s']*1000:.0f} ms after the completed two-second query. Files were processed faster than real time; this is not a live microphone latency measurement. The existing extractor can use the whole completed block, so no earlier framewise-causal output is claimed.</p>
    <h2>What this tells us</h2><p><b>The next bottleneck is evidence calibration across different amounts and qualities of surviving sound.</b> The present features often retain enough structure to propose the right memory and recover edits. The support rule does not reliably distinguish incomplete-but-informative evidence from insufficient support across lengths and observation failures.</p>
    <p>It would be premature to add more perturbations or replace the encoder based on this run. A subsequent bounded test should focus on support calibration while keeping these acoustic traces, competing accounts, and held-out controls. This report closes Experiment08; no new experiment has been started.</p>
    <p>The evidence concerns synthetic monophonic waveforms with supplied completed windows and an engineered event vocabulary. Real music, polyphony, continuous segmentation, human perceptual identity, and musical experience remain untested.</p>
    <h2>Reproducibility and preservation</h2><p>All {audit['earlier_files_unchanged']:,} previously tracked files are unchanged, including Experiments04–07 and the human pilot. The run generated 1,128 waveforms with 264 fresh base interval patterns disjoint from 1,032 earlier patterns. It extracted 1,080 descriptions; the 48 stacked development queries were deliberately unused.</p>
    <p>The audit recomputed all 13,824 trial decisions, reproduced the 1,200-pair readout fit and calibration choice, checked PCM/description hashes and freeze chronology, recomputed selected waveform pairs, and verified handle/order invariance. A relocated copy regenerated all 1,128 identical waveforms, re-extracted all 328 development blocks, reproduced coefficients and thresholds exactly, and matched four fresh held-out pair results. No test-driven predictor changes were made.</p>
    <div class="downloads"><p><a href="competing-accounts-kit.zip">Download reproducible experiment kit</a> · <a href="experiment08-milestone.md">Milestone record</a> · <a href="competing-accounts-data/protocol.json">Frozen evidence and scoring rules</a> · <a href="competing-accounts-data/summary.json">Machine-readable results</a> · <a href="competing-accounts-data/audit.json">Audit</a></p><p class="small">The kit contains source, generation provenance, frozen configurations, predictions, diagnostics, replay timestamps, report, figures, and instructions. All waveforms can be regenerated locally. Data paths in the archived original manifest reflect the original run; regeneration writes local paths.</p></div>
    </main></body></html>'''
    report=OUT/'competing-accounts-report.html';report.write_text(text)
    milestone=f'''# Earworm — Experiment08: Competing accounts\n\nCompleted September 19, 2026. Prior experiments and human pilot unchanged.\n\nExperiment08 is not a retrieval improvement: accepted correct source 164/576 versus frozen07 198/576; observed absent-source false acceptance 0/576 for both. The correct source ranks uniquely first in 553/576 source-present cases, a diagnostic that ignores rejection. Joint accepted retrieval plus strict programmed correspondence recovery is 156/576.\n\nMissing+transposition: 8/32 joint; missing+timing: 8/32; missing+detuning: 0/32. All three are first-ranked and recoverable with the known reference in 32/32 cases. No stacked edits enter development.\n\nEight accepted weak-note cases retain unresolved observation because energy remains where an event was not detected. All 64 masked cases are rejected; no successful masking-robust memory claim. Exact ambiguity sets: 4/16 cases, two orders each; prior reader 12/16. Substitution construction correspondence appears in 31/32 alternative sets vs 0/32 best paths with oracle reference; construction history is not uniquely audible.\n\n84 fresh replays / 840 blocks reproduce batch decisions; four future-prefix pairs invariant; reference-drop and reset remove source retrieval. Completed 2s windows and fixed-capacity explicit memory remain supplied. Output timestamps include extraction, matching and explanation; simulated arrivals, actual wall times.\n\n{audit['earlier_files_unchanged']:,} earlier files unchanged. All1128 WAVs regenerated identically in a relocated copy; development fit/calibration and four fresh held-out pairs reproduced. MERT untouched/unused. Paid external compute $0.\n\nNext research question: support calibration across surviving evidence quality and phrase length. No new experiment launched. No perceptual identity or subjective-hearing claim.\n\n[Report](competing-accounts-report.html) · [Reproducible kit](competing-accounts-kit.zip) · [Protocol](competing-accounts-data/protocol.json)\n'''
    (OUT/'experiment08-milestone.md').write_text(milestone)
    data=OUT/'competing-accounts-data';data.mkdir(exist_ok=True)
    for p in R.glob('*.json'):shutil.copy2(p,data/p.name)
    shutil.copy2(ROOT/'accounts_features/timings.json',data/'extraction_timings.json')
    kit=ROOT/'accounts_kit';work=prepare(kit);shutil.copy2(Path(__file__),work/Path(__file__).name);docs=kit/'outputs';docs.mkdir(exist_ok=True)
    for p in (report,chart,observation,OUT/'experiment08-milestone.md'):shutil.copy2(p,docs/p.name)
    shutil.copytree(data,docs/'competing-accounts-data',dirs_exist_ok=True)
    import scipy,sklearn
    (kit/'requirements.txt').write_text(f'numpy=={np.__version__}\nscipy=={scipy.__version__}\nscikit-learn=={sklearn.__version__}\nmatplotlib=={matplotlib.__version__}\n')
    (kit/'README.md').write_text('''# Earworm — Experiment08 reproducible kit

This archives the frozen September19 run, including its negative results. Python3.12 was used. NumPy/SciPy/scikit-learn perform local acoustic extraction and readout fitting; no MERT download, inference, training, remote compute, or human labels are required. The source renderer constructs mono 24kHz float WAVs. The original manifest embeds all exclusions needed for relocation.

Create a Python environment and install requirements.txt if these libraries are unavailable. From the extracted kit directory:

```sh
python -B work/accounts_stimuli.py --saved work/accounts_stimuli/manifest.json --outdir work/accounts_stimuli
python -B work/accounts_experiment.py develop
python -B work/accounts_experiment.py evaluate
python -B work/accounts_experiment.py replay
```

The generator rewrites the copied manifest with local paths and identical PCM. The runner verifies frozen source hashes. Development re-extracts328 blocks, refits1200 pairs and recalibrates; evaluation extracts752 held-out blocks and reproduces all frozen decisions. Regeneration takes roughly210MB, plus descriptors/results. Exact runtimes and timestamps vary by machine. Keep the archived work/accounts_results files elsewhere if you want to preserve their original timestamps before rerunning.

All1128 waveforms were regenerated in a relocated validation directory, coefficients/thresholds reproduced exactly, and four held-out waveform pairs checked. See portable_validation.json. Full fresh replay has84 trials and four future-prefix pairs. This is completed-window causal processing, not a live microphone test.

The original-workspace preservation audit in accounts_audit.py also checks12351 prior files; those prior experiments are intentionally not bundled, so run that preservation audit only in the original project. Its archived findings, replay records, raw predictions and scoring caveats are included. accounts_report.py additionally expects the original feature set, audit and portable-validation records; the completed standalone report and figures are already in outputs.

Metrics: ordinary origin retrieval is separate from human identity. Known-reference alignment ceilings and top-rank diagnostics are not accepted retrieval. Joint recovery applies only to the new reader; baseline summary zeros in that field mean not evaluated (raw trial fields are null). Masked rejections do not count as successful uncertainty-aware retrieval. Substitution/deletion-plus-insertion construction histories can explain the same waveform.

Open outputs/competing-accounts-report.html in a browser for the report and embedded playable examples. The packaged report's original download ZIP link is for the original project; you already have the kit.
''')
    zip_path=OUT/'competing-accounts-kit.zip'
    with zipfile.ZipFile(zip_path,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
        for p in sorted(kit.rglob('*')):
            if p.is_file():z.write(p,p.relative_to(kit))
    print(json.dumps({'report':str(report),'kit':str(zip_path),'zip_bytes':zip_path.stat().st_size,'ranked_first':ranked}))
if __name__=='__main__':main()
